# **Homework**

Trabajarás con la librería Numpy en Python para analizar las notas de un grupo de estudiantes. Asegúrate de tener Numpy instalado usando el comando pip install numpy.

1. Generar la Matriz de Notas:
* Genera una matriz de Numpy notas con dimensiones 20x5, donde cada elemento es una nota aleatoria entre 1 y 5 (pueden ser random.randint). Las filas representan a los estudiantes y las columnas representan diferentes asignaturas.
* Imprime la matriz generada.

In [7]:
import numpy as np

# Actividad 1: Creación de una Matriz de Notas

# Generar una matriz de notas de 20x5 con valores aleatorios entre 1 y 5
notas = np.random.randint(1, 6, size=(2, 5))
print("Matriz de Notas:")
print(notas)

Matriz de Notas:
[[4 5 2 5 1]
 [5 1 3 2 1]
 [4 3 5 1 2]
 [4 5 5 2 3]
 [1 2 5 1 3]
 [3 2 2 2 4]
 [2 3 3 2 3]
 [3 4 3 5 5]
 [3 5 5 4 3]
 [2 4 1 1 5]]


2. Seleccionar los Primeros 5 Estudiantes:
* Selecciona las notas de los primeros 5 estudiantes (filas) de la matriz y guárdalas en una nueva matriz notas_primeros_5.
* Imprime esta nueva matriz.

In [4]:
# Actividad 2: Selección de Estudiantes

# Seleccionar las notas de los primeros 5 estudiantes
#[[2 4 2 5 2]
# [1 2 3 3 5]]
notas_5 = notas[:2, :]
print("Notas de los primeros 5 estudiantes:")
print(notas_5)

Notas de los primeros 5 estudiantes:
[[5 3 5 4 4]
 [5 2 2 5 1]]


3. Calcular Promedio y Mediana:
* Calcula el promedio de notas para cada estudiante (fila) y guárdalo en un array promedios.
* Calcula la mediana de notas para cada estudiante y guárdala en un array medianas.
* Imprime los arrays promedios y medianas.

In [11]:
# Actividad 3: Estadísticas Básicas

# Calcular el promedio de notas por estudiante
promedios = np.mean(notas, axis=1)
print("Promedio de notas por estudiante:")
print(promedios)
print()

# Calcular la mediana de notas por estudiante
medianas = np.median(notas, axis=1)
print("Mediana de notas por estudiante:")
print(medianas)

Promedio de notas por estudiante:
[3.4 2.4 3.  3.8 2.4 2.6 2.6 4.  4.  2.6]

Mediana de notas por estudiante:
[4. 2. 3. 4. 2. 2. 3. 4. 4. 2.]


4. Crear una Máscara de Mejores Estudiantes:
* Crea una máscara que identifique a los estudiantes con una nota mayor o igual a 4.
* Imprime la matriz filtrada.

In [12]:
# Actividad 4: Estudiantes con Mejores Notas

# Crear una máscara para los estudiantes con nota mayor o igual a 4
mejores_estudiantes = notas >= 4

# Filtrar la matriz de notas usando la máscara
notas_mejores = notas[mejores_estudiantes]
print("Matriz de notas de los mejores estudiantes:")
print(notas_mejores)
print()

Matriz de notas de los mejores estudiantes:
[4 5 5 5 4 5 4 5 5 5 4 4 5 5 5 5 4 4 5]



5. Análisis de la Asignatura 3:
* Extrae las notas de la asignatura 3 (columna 2) para todos los estudiantes.
* Calcula y muestra el promedio, la mediana, el valor máximo y mínimo de estas notas.

In [13]:
# Actividad 5: Análisis de una Asignatura Específica

# Extraer las notas de la asignatura 3 (columna 2)
notas_asignatura_3 = notas[:, 2]
print("Notas de la asignatura 3:")
print(notas_asignatura_3)
print()

# Calcular estadísticas de la asignatura 3
promedio_asignatura_3 = np.mean(notas_asignatura_3)
mediana_asignatura_3 = np.median(notas_asignatura_3)
max_asignatura_3 = np.max(notas_asignatura_3)
min_asignatura_3 = np.min(notas_asignatura_3)

print(f"Promedio de la asignatura 3: {promedio_asignatura_3}")
print(f"Mediana de la asignatura 3: {mediana_asignatura_3}")
print(f"Nota máxima en la asignatura 3: {max_asignatura_3}")
print(f"Nota mínima en la asignatura 3: {min_asignatura_3}")

Notas de la asignatura 3:
[2 3 5 5 5 2 3 3 5 1]

Promedio de la asignatura 3: 3.4
Mediana de la asignatura 3: 3.0
Nota máxima en la asignatura 3: 5
Nota mínima en la asignatura 3: 1
